### ISSUE TITLE
Donation button adding 

### ISSUE THREAD

**Issue by Tharun-tharun** [Ximi1970/Donate#1]
Can you guide me on how to add my bitcoin address text in my "Donate Button" after clicking my donation button it should get me to the address text page just like yours, how do I do that. Thanks!

**Comment by Ximi1970** [comment]
First you need to generate the qr code png using the 'qrencode' command mentioned in the README.md changing my wallet address with yours.  
You need to install Gimp to edit the .xcf file and replace my qr png with yours. It is in a separate gimp "layer".  
Then export the image to a png format (or any other format you wish (and gimp supports).  
To get it linked in Github just open the raw README.md

**Comment by Tharun-tharun** [comment]
Sure will do that. Thanks this helps.
